{% set name = "pytorch_warmup" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}-pkg
  version: {{ version }}

source:
  url: https://github.com/Tony-Y/pytorch_warmup/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5599614d25eb276e8e84d0d21c4c62641751044eb3a7f9ac21165100be2239df

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build_python.sh

    build:
      noarch: python

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - pytorch >=1.1

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

  - name: pytorch-warmup
    build:
      noarch: generic

    requirements:
      run:
        - {{ name }} {{ version }}

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://pypi.org/project/pytorch_warmup
  doc_url: https://tony-y.github.io/pytorch_warmup/
  dev_url: https://github.com/Tony-Y/pytorch_warmup
  summary: A PyTorch Extension for Learning Rate Warmup
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
  feedstock-name: pytorch-warmup
